const ActionTypes = {
  SET_MARKUP: "SET_MARKUP",
  SET_IN_PROGRESS: "SET_IN_PROGRESS",
  SET_ERROR: "SET_ERROR",
  SET_SELECTED_FRAME: "SET_SELECTED_FRAME",
  RESET_APP_STATE: "RESET_APP_STATE",
};

export default ActionTypes;
